name: Text genUI
description: |
    Desc

author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-04-22"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Nvidia GPU

tasks:
  - type: run_session
    name: Install Dependencies
    script: setupscripts/1_session-install-deps/install_dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 8

  - type: create_job
    name: Download Models
    entity_label: download_data_and_models
    script: download-model.py EleutherAI/gpt-j-6B --text-only
    arguments: None
    short_summary: Create job to download pre-trained models. 
    long_summary: Create job to download open source pre-trained models. 
    cpu: 1
    memory: 4
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: download_data_and_models
    short_summary: Run job to download pre-trained models.
  
  - type: start_application
    name: Text Gen UI
    subdomain: cmlllm
    script: server.py
    short_summary: Start CML Text Gen UI
    long_summary: Start CML Text Gen UI........
    cpu: 2
    memory: 16
    environment_variables:
      TASK_TYPE: START_APPLICATION
